import type { Metadata } from "next";
import { Kanit} from "next/font/google";
import "./globals.css";

const kanit = Kanit({
  subsets: ["thai","latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});



export const metadata: Metadata = {
  title: "เว็บปลอม",// Add your title here
  description: "Generated by create next app", // Add your description here
  keywords: ["nextjs", "react", "typescript", "tailwindcss"], // Add your keywords here
  authors: [{ name: "Rattanakorn", url: "https://uiauia.com" }], // Add your author information here
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${kanit.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <h1 className="block text-center text-blue-900 font-bold"> WELCOME TO SAU</h1>
        {children}
      </body>
    </html>
  );
}
